#!/usr/bin/env python
# -*- coding: utf-8 -*-

from openbuild.commands import add

# Set default encoding to UTF-8
import sys
reload(sys)
sys.setdefaultencoding('utf8')


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print('Usgae: %s rev' % sys.argv[0])
    else:
        print(add(sys.argv[1]))
