#!/usr/bin/env python
# -*- coding: utf-8 -*-

from openbuild.commands import listbuilds

# Set default encoding to UTF-8
import sys
reload(sys)
sys.setdefaultencoding('utf8')

if __name__ == "__main__":
    if len(sys.argv) > 2:
        print('Usgae: %s [state]' % sys.argv[0])
    else:
        print(listbuilds(sys.argv[1] if len(sys.argv) == 2 else ''))
