#!/usr/bin/env python
# -*- coding: utf-8 -*-

from openbuild.commands import run
import sys


if __name__ == "__main__":
    if len(sys.argv) != 1:
        print('Usgae: %s' % sys.argv[0])
    else:
        run()
