#!/usr/bin/env python
# -*- coding: utf-8 -*-

from openbuild.commands import listbuilds
import sys

if __name__ == "__main__":
    if len(sys.argv) > 2:
        print('Usgae: %s [state]' % sys.argv[0])
    else:
        print(listbuilds(sys.argv[1] if len(sys.argv) == 2 else ''))
