#!/usr/bin/env python
# -*- coding: utf-8 -*-

from openbuild.commands import add
import sys


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print('Usgae: %s rev' % sys.argv[0])
    else:
        rev = sys.argv[1]
        if sys.version_info[0] == 2:
            rev = rev.decode('utf-8')
        print(add(rev))
